# Generated by Django 4.1.4 on 2022-12-19 07:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='globalSchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemaName', models.CharField(max_length=30)),
                ('schema', jsonfield.fields.JSONField()),
                ('localSchemas', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='localSchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemaName', models.CharField(max_length=30)),
                ('serverIP', models.CharField(max_length=30)),
                ('serverUser', models.CharField(max_length=30)),
                ('serverPass', models.CharField(max_length=30)),
                ('dbName', models.CharField(max_length=30)),
                ('schema', jsonfield.fields.JSONField()),
            ],
        ),
    ]
